name: Build Docker - Release
on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build-docker:
    name: Build Docker - Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          ref: release/22.0.x
          token: ${{ github.token }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0
      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@1bc1040caef9e604eb543693ba89b5bf4fc80935
        with:
          context: ./.github/eosjs-ci
          file: ./.github/eosjs-ci/Dockerfile
          pull: true
          push: true
          no-cache: true
          build-args: |
            EOSBRANCH=release_2.1.x
            CDTBRANCH=release_1.8.x
          tags: |
            eosio/eosjs-ci:release_22.0.x
            eosio/eosjs-ci:${{ github.sha }}
