name: Integration Tests
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  integration-test-release_22_0_x-release_2_0_x:
    name: Integration Test 
    - eosjs release/22.0.x with nodeos release/2.0.x
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout
        - "@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f"
        with:
          ref: release/22.0.x
      - name: Setup Node.js v20.x.x
        uses: actions/setup
        - "node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea"
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: |
          yarn --frozen
          - lockfile
      - name: Test
        run: |
          yarn test
      - name: Test Node
        run: |
          yarn test-node-coverage
        env:
          NODEOS_VER: 'release/20.x'
          COVERAGE_TESTING: true
      - name: Copy Coverage Files
        run: |
          mkdir -p ./coverage/multiple-sources
          cp ./coverage/test/coverage-final.json
          ./coverage/multiple-sources/test.json
          cp 
          ./coverage/test-node/coverage-final.json
          ./coverage/multiple-sources/test-node.json
          ./node_modules/nyc/bin/nyc.js
          merge
          ./coverage/multiple-sources 
          ./coverage/merged-output/coverage.json
          ./node_modules/nyc/bin/nyc.js
          report
          -t ./coverage/merged
          -output --report
          -dir ./coverage/merged
          -report
          --reporter
          =html
      - name: Build
        run: |
          yarn build-web
      - name: Test Web
        uses: cypress-io/github-action@1db146275576798796bc39ef83d739924145298a
        with:
          spec: cypress/integration/index.spec.js
        env:
          CYPRESS_NODEOS_VER: 'release/20.x'
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: nodeos-release_2.0.x-eosjs-release_22.0.x-coverage
          path: coverage/merged-report
    services:
      nodeos:
        image: eosio/eosjs-ci:release_20.x
        ports:
          - 443 : 8080
